package mastermind;

//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Sun 27-Nov-2011 by the VDM++ to JAVA Code Generator
// (v8.0 - Mon 09-Jul-2007 09:32:40)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import jp.co.csk.vdm.toolbox.VDM.jdk.*;
// ***** VDMTOOLS END Name=imports



public class Color implements EvaluatePP {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=Colors KEEP=NO
  public volatile static HashSet Colors = new HashSet();
// ***** VDMTOOLS END Name=Colors

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=ColorSentinel KEEP=NO
  class ColorSentinel extends Sentinel {

    public final int randomColor = 0;

    public final int getRandomSequence = 1;

    public final int nr_functions = 2;


    public ColorSentinel () throws CGException {}


    public ColorSentinel (EvaluatePP instance) throws CGException {
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=ColorSentinel
;

// ***** VDMTOOLS START Name=evaluatePP KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException {
    return new Boolean(true);
  }
// ***** VDMTOOLS END Name=evaluatePP


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try {
      sentinel = new ColorSentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=static KEEP=NO
  static {
    try {

      Color.Colors = new HashSet();
      Color.Colors.add(new Character('b'));
      Color.Colors.add(new Character('g'));
      Color.Colors.add(new Character('r'));
      Color.Colors.add(new Character('o'));
      Color.Colors.add(new Character('y'));
      Color.Colors.add(new Character('m'));
    }
    catch (Throwable e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=static


// ***** VDMTOOLS START Name=inv_Color KEEP=NO
  public Boolean inv_Color (final Character color) throws CGException {

    Boolean varRes_2 = null;
    HashSet var2_4 = new HashSet();
    var2_4 = new HashSet();
    var2_4.add(new Character('b'));
    var2_4.add(new Character('g'));
    var2_4.add(new Character('r'));
    var2_4.add(new Character('o'));
    var2_4.add(new Character('y'));
    var2_4.add(new Character('m'));
    varRes_2 = new Boolean(var2_4.contains(color));
    return varRes_2;
  }
// ***** VDMTOOLS END Name=inv_Color


// ***** VDMTOOLS START Name=Color KEEP=NO
  public Color () throws CGException {
    try {
      setSentinel();
    }
    catch (Exception e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=Color


// ***** VDMTOOLS START Name=getRandomSequence KEEP=NO
  static public String getRandomSequence (final Integer length) throws CGException {
    if (new Boolean(length.intValue() == new Integer(1).intValue()).booleanValue()) {

      String rexpr_12 = null;
      rexpr_12 = new String();
      rexpr_12 = rexpr_12 + randomColor();
      return rexpr_12;
    }
    else {

      String rexpr_5 = null;
      String var1_6 = null;
      var1_6 = new String();
      var1_6 = var1_6 + randomColor();
      rexpr_5 = var1_6.concat(getRandomSequence(new Integer(length.intValue() - new Integer(1).intValue())));
      return rexpr_5;
    }
  }
// ***** VDMTOOLS END Name=getRandomSequence


// ***** VDMTOOLS START Name=randomColor KEEP=NO
  static private Character randomColor () throws CGException {

    Random rand = new Random();

    Character[] array = {new Character('b'), new Character('g'), new Character('r'), new Character('o'), new Character('y'), new Character('m')};

    return array[rand.nextInt(array.length)];
  }
// ***** VDMTOOLS END Name=randomColor


}
;
